name: Core C CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: setup (macos)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install cmake

    - name: setup (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y --no-install-recommends cmake valgrind time curl

    #- name: Setup libfec
    #  run: git clone https://github.com/jgaeddert/libfec.git && cd libfec && ./configure && make && sudo make install

    - name: build
      run: |
        mkdir build
        cd build
        cmake -DBUILD_AUTOTESTS=ON -DBUILD_BENCHMARKS=ON -DBUILD_EXAMPLES=ON ..
        make -j2

    - name: check
      run: |
        cd build
        ./xautotest -v -o autotest.json

    - name: make install
      run: |
        cd build
        sudo make install

    - name: ldconfig (Linux)
      if: runner.os == 'Linux'
      run: sudo ldconfig

    - name: check installation
      run: make -f scripts/liquid_linker_test.mk

